#ifndef PORTS
#define PORTS
const int ALICE_FRONTEND_ALICE_BACKEND = 8080;
const int ALICE_SERVER_BOB_CLIENT = 8091;
const int BOB_FRONTEND_BOB_BACKEND = 8083;
const int BOB_SERVER_ALICE_CLIENT = 8092;
#endif