#ifndef PORTS
#define PORTS
const int ALICE_FRONTEND_ALICE_BACKEND = ALICE_FRONTEND_ALICE_BACKEND_VALUE;
const int ALICE_SERVER_BOB_CLIENT = ALICE_SERVER_BOB_CLIENT_VALUE;
const int BOB_FRONTEND_BOB_BACKEND = BOB_FRONTEND_BOB_BACKEND_VALUE;
const int BOB_SERVER_ALICE_CLIENT = BOB_SERVER_ALICE_CLIENT_VALUE;
#endif