# Generated by Django 5.0.6 on 2024-11-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="connected_users",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="document",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="CursorPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("position", models.IntegerField(default=0)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docs_app.document",
                    ),
                ),
            ],
        ),
    ]
