# Generated by Django 5.0.6 on 2024-11-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs_app", "0002_document_connected_users_document_last_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.IntegerField(default=0),
        ),
    ]
